version: '3'
services:
  dbservice:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Vasu193204@
      - MYSQL_DATABASE=electronic_store1
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - bootapp

  appservice:
    build: .
    depends_on:
      - dbservice
    environment:
      - spring.datasource.url=jdbc:mysql://dbservice:3306/electronic_store1?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=Vasu193204@
    ports:
      - 8080:8080
    networks:
      - bootapp

networks:
  bootapp:
