server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/electronic_store1
spring.datasource.username=root
spring.datasource.password=Vasu193204@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
#This setting tells Hibernate (the JPA implementation in Spring Boot) how to handle the database schema when the application starts.
spring.jpa.show-sql=true
#to enable the logging of SQL queries that are generated and executed by Hibernate (JPA provider).
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#This tells Hibernate (the JPA provider in Spring Boot) to use the MySQL 8 specific SQL dialect when generating queries.